name: japanese-pref-workflow

on: 
  push:
  workflow_dispatch: 
  schedule: ""


jobs: 
  run-app: 
  runs-on: ubuntu-latest
  steps:
    - name: checkout repo content
      uses: actions/checkout@v4
      with: 
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: setup python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.9'
        cache: pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: run app
      run: python3 main.py
    - name: Check for changes
      id: git-check
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add .
        git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV


